"""MLP baseline for supervised play policy prediction."""

from __future__ import annotations

from .actor_critic import (
    ACTOR_CRITIC_ALGORITHM,
    DEFAULT_VALUE_LOSS_COEFFICIENT,
    ActorCriticTrainReport,
    ActorCriticTrainSettings,
    actor_critic_losses,
    train_policy_actor_critic,
)
from .checkpoint import (
    ACTOR_CRITIC_MODEL_ARCHITECTURE,
    CHECKPOINT_SCHEMA_VERSION,
    POLICY_MODEL_ARCHITECTURE,
    PolicyCheckpointCompatibilityError,
    load_policy_checkpoint,
    load_policy_logits_checkpoint,
    migrate_policy_checkpoint_to_hidden_dims,
    migrate_policy_checkpoint_v1_to_v2,
    save_policy_checkpoint,
)
from .metrics import (
    PolicyEvaluationReport,
    PolicyMetric,
    evaluate_policy_model,
    mask_illegal_policy_logits,
    masked_policy_accuracy,
    masked_policy_cross_entropy,
    select_policy_action,
)
from .model import (
    PolicyActorCriticModel,
    PolicyMlpConfig,
    PolicyMlpModel,
    create_actor_critic_from_policy_model,
    create_seeded_actor_critic_model,
    create_seeded_policy_model,
)
from .onnx_export import (
    ONNX_INPUT_NAME,
    ONNX_OUTPUT_NAME,
    POLICY_ONNX_METADATA_SCHEMA_VERSION,
    PolicyOnnxExportReport,
    build_policy_onnx_metadata,
    export_policy_checkpoint_to_onnx,
    validate_policy_onnx_metadata,
)
from .reinforce import (
    BEHAVIOR_LOG_PROB_PARITY_ATOL,
    BEHAVIOR_LOG_PROB_PARITY_RTOL,
    REINFORCE_ALGORITHM,
    ReinforceTrainReport,
    ReinforceTrainSettings,
    masked_selected_log_probability,
    reinforce_policy_loss,
    train_policy_reinforce,
)

__all__ = [
    "CHECKPOINT_SCHEMA_VERSION",
    "ACTOR_CRITIC_ALGORITHM",
    "ACTOR_CRITIC_MODEL_ARCHITECTURE",
    "DEFAULT_VALUE_LOSS_COEFFICIENT",
    "POLICY_MODEL_ARCHITECTURE",
    "ActorCriticTrainReport",
    "ActorCriticTrainSettings",
    "PolicyCheckpointCompatibilityError",
    "PolicyEvaluationReport",
    "PolicyMetric",
    "PolicyActorCriticModel",
    "PolicyMlpConfig",
    "PolicyMlpModel",
    "PolicyOnnxExportReport",
    "ONNX_INPUT_NAME",
    "ONNX_OUTPUT_NAME",
    "POLICY_ONNX_METADATA_SCHEMA_VERSION",
    "BEHAVIOR_LOG_PROB_PARITY_ATOL",
    "BEHAVIOR_LOG_PROB_PARITY_RTOL",
    "REINFORCE_ALGORITHM",
    "actor_critic_losses",
    "build_policy_onnx_metadata",
    "create_actor_critic_from_policy_model",
    "create_seeded_actor_critic_model",
    "create_seeded_policy_model",
    "evaluate_policy_model",
    "export_policy_checkpoint_to_onnx",
    "load_policy_checkpoint",
    "load_policy_logits_checkpoint",
    "mask_illegal_policy_logits",
    "migrate_policy_checkpoint_v1_to_v2",
    "migrate_policy_checkpoint_to_hidden_dims",
    "masked_selected_log_probability",
    "masked_policy_accuracy",
    "masked_policy_cross_entropy",
    "reinforce_policy_loss",
    "ReinforceTrainReport",
    "ReinforceTrainSettings",
    "save_policy_checkpoint",
    "select_policy_action",
    "train_policy_actor_critic",
    "train_policy_reinforce",
    "validate_policy_onnx_metadata",
]
